# Generated by Django 3.2.4 on 2021-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Addr', models.TextField()),
                ('Tele', models.TextField()),
                ('Mono', models.TextField(blank=True, null=True)),
                ('Monc', models.TextField(blank=True, null=True)),
                ('Tueo', models.TextField(blank=True, null=True)),
                ('Tuec', models.TextField(blank=True, null=True)),
                ('Wedo', models.TextField(blank=True, null=True)),
                ('Wedc', models.TextField(blank=True, null=True)),
                ('Thuo', models.TextField(blank=True, null=True)),
                ('Thuc', models.TextField(blank=True, null=True)),
                ('Frio', models.TextField(blank=True, null=True)),
                ('Fric', models.TextField(blank=True, null=True)),
                ('Sato', models.TextField(blank=True, null=True)),
                ('Satc', models.TextField(blank=True, null=True)),
                ('Suno', models.TextField(blank=True, null=True)),
                ('Sunc', models.TextField(blank=True, null=True)),
                ('Hpid', models.TextField()),
                ('Etc', models.TextField(blank=True, null=True)),
                ('Info', models.TextField(blank=True, null=True)),
                ('Map', models.TextField(blank=True, null=True)),
                ('Todr', models.TextField(blank=True, null=True)),
                ('medr', models.TextField(blank=True, null=True)),
                ('dedr', models.TextField(blank=True, null=True)),
                ('cmdr', models.TextField(blank=True, null=True)),
                ('hgSi', models.TextField(blank=True, null=True)),
                ('stSi', models.TextField(blank=True, null=True)),
                ('adSp', models.TextField(blank=True, null=True)),
                ('nbSp', models.TextField(blank=True, null=True)),
                ('paCn', models.TextField(blank=True, null=True)),
                ('soCn', models.TextField(blank=True, null=True)),
                ('emCn', models.TextField(blank=True, null=True)),
                ('ptCn', models.TextField(blank=True, null=True)),
                ('chCn', models.TextField(blank=True, null=True)),
                ('pshgCn', models.TextField(blank=True, null=True)),
                ('psstCn', models.TextField(blank=True, null=True)),
                ('isCn', models.TextField(blank=True, null=True)),
                ('anCn', models.TextField(blank=True, null=True)),
                ('emDy', models.TextField(blank=True, null=True)),
                ('emNg', models.TextField(blank=True, null=True)),
                ('paQt', models.TextField(blank=True, null=True)),
                ('dgsb', models.TextField(blank=True, null=True)),
                ('srch', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
