# Generated by Django 3.2.4 on 2021-07-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Holc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Holo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
